// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nparpxadahvbwimqiiyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wYXJweGFkYWh2YndpbXFpaXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDczNzEsImV4cCI6MjA3MDAyMzM3MX0.-H2zAfYyMxDaf8ygDyap1-FPbDHy_8XduH4oHHUanFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});